<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <UserSecretsId>dotnet-TeleQ.Messaging.Worker-18db5202-d381-48cd-92e5-7ec99e521b8a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.RabbitMQ.Client" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Aspire\TeleQ.ServiceDefaults\TeleQ.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
