<Project Sdk="Microsoft.NET.Sdk.Web">
	<ItemGroup>
		<PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Aspire.Keycloak.Authentication" />
		<PackageReference Include="FastEndpoints" />
		<PackageReference Include="FastEndpoints.AspVersioning" />
		<PackageReference Include="FastEndpoints.OpenApi" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="Marten" />
		<PackageReference Include="Marten.AspNetCore" />
		<PackageReference Include="JasperFx.Events.SourceGenerator">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Mediator.Abstractions" />
		<PackageReference Include="Mediator.SourceGenerator">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Scalar.AspNetCore.Microsoft" />
		<PackageReference Include="Telegram.Bot" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Aspire\TeleQ.ServiceDefaults\TeleQ.ServiceDefaults.csproj" />
	</ItemGroup>
</Project>
